# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            FFIM
tagline:          'Salut!'
description:      'Aspiring <a href="http://jekyllrb.com" target="_blank">Developer</a> | +65 Singapore | Favourite Mantra: <a href="https://twitter.com/mdo" target="_blank">Fail Fast, Iterate More</a>.'
url:              https://jiawenling.github.io
baseurl:          /

author:
  name:           JiawennLing
  url:            www.linkedin.com/in/lingjiawen

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
