# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Faire
tagline:          'Road to development'
description:      'Aspiring Developer | Evader of repetitive stuff | +65 Singapore | Mantra: Fail Fast, Iterate More'
url:              https://jiawenling.github.io
#baseurl:          ""

author:
  name:           'Ling Jia Wen'
  url:            www.linkedin.com/in/lingjiawen

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
  - jekyll-paginate
  - jekyll-gist
